### ISSUE TITLE
Service provider configuration

### ISSUE THREAD

**Issue by mbabker** [chrisdavenport/service#3]
The service providers should register class names (and interfaces if appropriate) in addition to the "short name" alias.  This helps to support the container's auto-wiring features (when running $container->buildObject()) and provides a clearer definition of what classes/interfaces the provider is registering.

**Comment by chrisdavenport** [comment]
Interesting.  However, after some experimentation I decided that the container just wasn't needed and so I dropped it in favour of a builder class.  Your feedback on this new approach would be very welcome.

**Comment by mbabker** [comment]
The Framework's site has a few examples of auto-wiring working side-by-side with fully registered services.  For example, the [DefaultController::initializeModel()](https://github.com/joomla/framework.joomla.org/blob/master/src/Controller/DefaultController.php#L70-L96) will assemble the model classes there by using the DI container to read the constructor arguments (the database driver and a Registry object for the model's state), then the container will look to see if it has services for those defined (there's a [DatabaseProvider](https://github.com/joomla/framework.joomla.org/blob/master/src/Service/DatabaseProvider.php)) and inject the service if not found.  If the argument is something that can be instantiated by the container (a Registry instance is), it'll just dump a new object into that argument if a service isn't found.  So it's good to define services using fully qualified class names for this aspect of the container (and you can still alias that service to any other name you want; in other projects I have application services which are aliased as every parent class up the chain to cover all bases).

And ya, I agree the container was probably overkill for how this is currently structured.  You could though continue to provide basic service provider configurations if the builders are compatible as an optional way to demonstrate how one could use this layer in their full application (or just consume the providers you've given in full, plenty of options).  We did this with the Framework's database package on the 2.0 branch (there's a [basic service provider](https://github.com/joomla-framework/database/blob/2.0-dev/src/Service/DatabaseProvider.php) to get a database driver included in the tree without a hard dependency to the container).
